Give motivation of extracting from different sources and some numbers that supports the argument, that relations that can be found in QnA entity pairs cannot be extracted from individual sentences.\\
- Statistics from Y!Answers dataset on location of different triples\\
- How many of QnA triples can be found within a sentence in Clueweb\\
- analyze predicates that occur more often in Q\&A pairs rather than individual sentences (examples of predicates, functional vs non-functional predicates)